### ISSUE TITLE
eth0 hard coded line 70

### ISSUE THREAD

**Issue by mathieuchateau** [willemdh/generate_motd#1]
eth0 is expected line 70 in generate_motd.sh.
It should be at least a variable at the top of the file.

On all my CentOS7 VM, no eth0 but ens160 instead (vmware)

**Comment by willemdh** [comment]
Hey Mathieu,

Thanks for letting me know. I changed some parts of the code so it no longer needs ifconfig. Instead I'm using ip route to get the ip address. Does this work for you?

Grtz

Willem

**Comment by willemdh** [comment]
No confirmation from @mathieuchateau , I'm considering this solved.
