### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by brendanmullan** [willemdh/generate_motd#2]
Hey just wanted to say thanks for this, simple and really effective! Awesome job! :+1:

**Comment by willemdh** [comment]
@brendanmullan Thanks Brendan, I like it too and I'm using it everywhere :) Using the red theme for production servers and blue for QA / DEV / test systems. I've got a lot of improvements planned, but got my hands full atm with other stuff.

**Comment by brendanmullan** [comment]
Exactly what I'm using it for! It's so nice to see the server stats on login, saves me looking.

Look forward to seeing what you have planned! :smile:
